import Link from 'next/link';
import {ArrowRight,ShieldCheck,TrendingUp,Users,Zap} from 'lucide-react';
import Shell from '@/components/Shell';
import TokenCard from '@/components/TokenCard';
import {getCreatedTokens} from '@/lib/onchain';

export const dynamic='force-dynamic';

export default async function Home(){
  const live=await getCreatedTokens();
  const liveTokens=live.map(t=>({address:t.address,name:t.name,symbol:t.symbol,creator:t.creator,description:t.description||'Creator token launched on Robinhood Chain.',marketCap:'—',volume:'—',holders:'—',progress:0,status:'Bonding' as const,color:'lime',logo:t.metadataURI||'https://api.dicebear.com/9.x/shapes/svg?seed='+t.address}));
  return <Shell><main><section className="hero"><div className="shell"><span className="eyebrow"><i className="dot"/> Permissionless creator launchpad</span><h1>Turn your idea into a token people can discover.</h1><p>Launch creator-owned tokens on Robinhood Chain with real wallet transactions, transparent reserves, creator fee tracking and onchain discovery.</p><div className="hero-actions"><Link className="btn primary" href="/launch">Launch a token <ArrowRight size={15}/></Link><Link className="btn" href="#discover">Explore launches</Link></div><div className="metrics"><div className="metric"><label>LIVE TOKENS</label><strong>{live.length}</strong></div><div className="metric"><label>CHAIN</label><strong>4663</strong></div><div className="metric"><label>CREATOR FEE</label><strong>1%</strong></div><div className="metric"><label>TRADING</label><strong>ONCHAIN</strong></div></div></div></section><section id="discover" className="section"><div className="shell"><div className="sectionhead"><div><h2>Live launches</h2><p>Every token shown here comes from the configured Hoodlaunch factory.</p></div><div className="filters"><span className="filter active">Onchain</span><span className="filter">Robinhood Chain</span></div></div>{liveTokens.length?<div className="grid">{liveTokens.map(t=><TokenCard key={t.address} token={t}/>)}</div>:<div className="card cardpad empty-state"><Zap size={22} color="var(--lime)"/><h3>No launches yet</h3><p className="muted">Deploy the Hoodlaunch factory and create the first token to populate this market.</p><Link className="btn primary" href="/launch">Launch first token <ArrowRight size={14}/></Link></div>}</div></section><section className="section"><div className="shell"><div className="card" style={{padding:24,display:'grid',gridTemplateColumns:'1.5fr 1fr',gap:25,alignItems:'center'}}><div><span className="eyebrow"><Zap size={12}/> Built for creators</span><h2 style={{fontSize:30,letterSpacing:'-.05em',margin:'13px 0 8px'}}>Own the launch. Keep earning.</h2><p className="muted" style={{maxWidth:650,fontSize:13,lineHeight:1.6}}>Hoodlaunch is designed around creator ownership: transparent token deployment, a dedicated earnings dashboard, shareable token pages and onchain claim flows.</p><Link className="btn primary" href="/launch" style={{marginTop:14}}>Create your first token <ArrowRight size={14}/></Link></div><div style={{display:'grid',gap:9}}><div className="mini-grid"><div><label><ShieldCheck size={12}/> ONCHAIN</label><strong>Transparent contracts</strong></div><div><label><TrendingUp size={12}/> DISCOVERY</label><strong>Live reserve data</strong></div></div><div className="mini-grid"><div><label><Users size={12}/> CREATOR</label><strong>Own your community</strong></div><div><label><Zap size={12}/> FEES</label><strong>Claimable rewards</strong></div></div></div></div></div></section></main></Shell>
}
